DROP TABLE IF EXISTS user_vocabulary;
DROP TABLE IF EXISTS vocabulary;
DROP TABLE IF EXISTS user_lessons;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS user_languages;
DROP TABLE IF EXISTS users;
